### ISSUE TITLE
build system: either automake or cmake?

### ISSUE THREAD

**Issue by aewallin** [lxi-tools/python-liblxi#1]
the current cmake build requires autogen/configure to generate "config.h" - this isn't ideal since we require parts of both build systems to make it work.

we should use only one build system, either automake or cmake.

**Comment by lundmar** [comment]
I'm sorry but lxi-tools and liblxi are not going to switch away from autotools anytime soon. Autotools has its quirks but it is still the defacto standard that users are most familiar with. However, I don't mind if you use cmake for python-liblxi. I will leave that for you to decide :)

**Comment by lundmar** [comment]
Oh, and by the way, you should not use config.h. This file is only for internal use when building the liblxi library. When installing liblxi it only installs the following files which can be used by python-liblxi:

```
.
├── include
│   └── lxi.h
├── lib
│   ├── liblxi.a
│   ├── liblxi.la
│   ├── liblxi.so -> liblxi.so.1.0.0
│   ├── liblxi.so.1 -> liblxi.so.1.0.0
│   └── liblxi.so.1.0.0
└── share
    └── man
        └── man3
            ├── lxi_connect.3
            ├── lxi_disconnect.3
            ├── lxi_discover.3
            ├── lxi_init.3
            ├── lxi_receive.3
            └── lxi_send.3
```
